[workflow]
dataset = ''
access_level = 'test'
name = 'TEST_RUN'

[mutect2_chip]
intervals = 'OPTIONAL_FILE'
ref_fasta = 'REQUIRED_FILE'
ref_fai = 'REQUIRED_FILE'
ref_dict = 'REQUIRED_FILE'
bam_bai_list = './input/inputFiles.tsv'
vcf_idx_list = 'OPTIONAL_TSV_FILE'
scatter_count = 10
gnomad = 'REQUIRED_FILE'
gnomad_idx = 'REQUIRED_FILE'
m2_extra_args = '--pcr-indel-model NONE --downsampling-stride 20 --max-reads-per-alignment-start 6 --max-suspicious-reads-per-alignment-start 6'
m2_only = false
create_pon_extra_args = 'OPTIONAL_STRING'
compress = true
pon_name = 'REQUIRED_STRING'
min_contig_size = 1000000
create_panel_scatter_count = 24
gatk_docker = 'australia-southeast1-docker.pkg.dev/pb-dev-312200/somvar-images/gatk@sha256:0359ae4f32f2f541ca86a8cd30ef730bbaf8c306b9d53d2d520262d3e84b3b2b'
gatk_override = 'OPTIONAL_FILE'
preemptible = 2
max_retries = 2
small_task_cpu = 4
small_task_mem = 4000
small_task_disk = 100
command_mem_padding = 1000
boot_disk_size = 12
m2_mem = 5000
m2_cpu = 4
pon_mem = 5000
small_input_to_output_multiplier = 2.0
cram_to_bam_multiplier = 6.0
